In [1]:
#1.	Préparer un dataset de classification binaire (ex. critiques positives vs négatives)

In [46]:
import re
import csv

In [41]:
#Recuperation des données dans une liste commentaire positif
commentaire_positif=["""
"Messi est un génie, il fait rêver le monde du football.",positif
"Chaque fois qu’il touche le ballon, on sent la magie.",positif
"Il est une légende vivante, incomparable dans l’histoire du sport.",positif
"Sa vision de jeu est exceptionnelle, il fait briller toute son équipe.",positif
"Je suis impressionné par sa constance même après tant d’années.",positif
"Sans Messi, le football ne serait pas le même.",positif
"Son humilité en dehors du terrain le rend encore plus grand.",positif
"Il mérite largement tous ses Ballons d’Or.",positif
"Messi est la définition du mot talent.",positif
"Voir Messi jouer est un privilège pour notre génération.",positif
"Sa technique est tout simplement irréaliste.",positif
"Messi peut changer le cours d’un match en une seconde.",positif
"Il est un modèle pour les jeunes footballeurs.",positif
"Chaque dribble de Messi est une œuvre d’art.",positif
"Il inspire des millions de personnes dans le monde.",positif
"Messi est synonyme de régularité et d’excellence.",positif
"Il fait briller ses coéquipiers autant que lui-même.",positif
"Messi est un leader silencieux mais efficace.",positif
"Ses passes décisives sont aussi belles que ses buts.",positif
"On ne reverra peut-être plus jamais un joueur de son niveau.",positif
"Messi rend le football spectaculaire.",positif
"Sa vision du jeu est unique au monde.",positif
"Messi est un artiste du ballon rond.",positif
"Chaque match avec Messi est un cadeau.",positif
"Il a marqué une époque entière du football.",positif
"Messi est respecté même par ses rivaux.",positif
"Il reste humble malgré son immense succès.",positif
"Il a toujours su se réinventer avec l’âge.",positif
"Messi rend ses coéquipiers meilleurs.",positif
"Il joue avec une intelligence rare.",positif
"Messi incarne la passion du football.",positif
"Il est la fierté de millions de fans.",positif
"Messi est le joueur le plus complet de tous les temps.",positif
"Il a réécrit les records du football.",positif
"Messi joue pour l’équipe avant tout.",positif
"Il ne triche jamais sur le terrain.",positif
"Ses dribbles défient les lois de la physique.",positif
"Messi a inspiré une génération entière.",positif
"Il a toujours respecté le jeu et ses adversaires.",positif
"Messi est une icône mondiale.",positif
"Chaque but de Messi est un moment d’histoire.",positif
"Il fait rêver même ceux qui ne suivent pas le foot.",positif
"Messi est une légende déjà vivante.",positif
"Il rend le football plus beau à regarder.",positif
"Messi a toujours répondu présent dans les grands moments.",positif
"Son jeu de passes est une masterclass.",positif
"Messi est la preuve que le talent pur existe.",positif
"Il a porté son pays au sommet avec la Coupe du Monde.",positif
"Messi a un palmarès incroyable et mérité.",positif
"Il restera une référence pour toujours.",positif
"Messi est une source d’inspiration.",positif
"Il est l’icône ultime du football moderne.",positif
"Messi est un exemple de professionnalisme.",positif
"Il a transformé Barcelone en légende.",positif
"Messi a marqué chaque compétition où il a joué.",positif
"Il a toujours été fidèle à son club et à ses valeurs.",positif
"Messi a toujours montré un jeu propre et élégant.",positif
"Il a été décisif dans des centaines de matchs.",positif
"Messi est respecté dans le monde entier.",positif
"Il est resté constant malgré la pression.",positif
"Messi est un joueur qui unit les fans.",positif
"Il a gravé son nom dans l’histoire du football.",positif
"Chaque match avec Messi est une leçon.",positif
"Messi est une fierté pour l’Argentine.",positif
"Il a accompli ce que peu de joueurs ont réussi.",positif
"Messi a toujours fait preuve de loyauté.",positif
"Il est l’un des joueurs les plus aimés au monde.",positif
"Messi est une légende incontestable.",positif
"Il a rendu possible l’impossible.",positif
"Messi est une inspiration pour les générations futures.",positif
"Il est le rêve de tout supporter.",positif
"Messi a écrit les plus belles pages du football.",positif
"Il restera à jamais une référence.",positif
"Messi a dominé son époque.",positif
"Il est l’icône du beau jeu.",positif
"Messi est un maître du ballon rond.",positif
"Il a inspiré des millions d’enfants.",positif
"Messi est le symbole de la réussite.",positif
"Il a donné au football une autre dimension.",positif
"Messi a conquis le monde par son talent.",positif
"Il a toujours été fidèle à ses principes.",positif
"Messi est le roi du football.",positif
"Il est l’incarnation du joueur parfait.",positif
"Messi a illuminé chaque stade où il a joué.",positif
"Il a changé l’histoire du FC Barcelone.",positif
"Messi est le plus grand de tous les temps.",positif
"Il a apporté du bonheur à des millions de fans.",positif
"Messi a inspiré respect et admiration.",positif
"Il a marqué une génération entière.",positif
"Messi est un joueur hors norme.",positif
"Il restera à jamais gravé dans l’histoire.",positif
"Messi est une étoile éternelle du football.",positif
"Il a toujours répondu présent pour son pays.",positif
"Messi est la définition de l’excellence.",positif
"Il est un joueur unique en son genre.",positif
"Messi restera une légende pour toujours.",positif
"Il est le joueur le plus admiré de sa génération.",positif
"Messi a transcendé le football.",positif
"Il restera dans les mémoires à jamais.",positif
"Messi est l’essence même du football.",positif
"Il est un mythe vivant.",positif
"Messi a fait vibrer le monde entier.",positif"""]

#Commentaire negaifs
commentaire_negatif=["""
"Messi est trop surcoté",negatif
"Il disparaît souvent dans les grands matchs.",negatif
"Sans Barcelone, il n’aurait jamais eu autant de titres.",negatif
"Il n’a pas la même influence en sélection qu’en club.",negatif
"On le compare à Pelé et Maradona, mais il n’a pas le même impact historique.",negatif
"Il ne défend presque jamais, il laisse tout le travail aux autres.",negatif
"Ses performances au PSG étaient décevantes.",negatif
"Il dépend trop de ses coéquipiers pour briller.",negatif
"Messi est fragile physiquement, il se cache quand le jeu devient dur.",negatif
"Il n’aurait pas dû gagner certains de ses Ballons d’Or.",negatif
"Messi n’a pas réussi à s’imposer hors d’Espagne.",negatif
"Il n’a pas toujours été décisif en Coupe du Monde.",negatif
"Messi est protégé par les arbitres.",negatif
"Il a trop souvent échoué en finale avant 2022.",negatif
"Il ne peut pas porter une équipe tout seul.",negatif
"Messi manque de charisme comme leader.",negatif
"Ses statistiques gonflent contre de petites équipes.",negatif
"Il a échoué plusieurs fois avec l’Argentine.",negatif
"Messi n’est pas aussi complet que certains le disent.",negatif
"Il disparaît quand le match est difficile.",negatif
"Messi ne prend pas assez de risques sur le terrain.",negatif
"Il est moins décisif que d’autres légendes.",negatif
"Messi a eu la chance de jouer avec Xavi et Iniesta.",negatif
"Il n’est pas aussi influent hors du terrain.",negatif
"Messi ne peut pas rivaliser physiquement avec d’autres joueurs.",negatif
"Il a parfois manqué de mental dans les grands matchs.",negatif
"Messi n’a pas réussi à briller partout.",negatif
"Il a échoué à marquer dans plusieurs finales.",negatif
"Messi dépend trop du collectif.",negatif
"Il a profité d’un système construit autour de lui.",negatif
"Messi est moins spectaculaire qu’avant.",negatif
"Il ne prend pas assez de responsabilités.",negatif
"Messi n’a pas toujours su être décisif.",negatif
"Il est resté trop longtemps à Barcelone.",negatif
"Messi a fui la difficulté en quittant l’Espagne.",negatif
"Il n’est pas le meilleur de sa génération.",negatif
"Messi a souvent déçu en Ligue des Champions.",negatif
"Il a parfois échoué face à des équipes moyennes.",negatif
"Messi n’est pas assez combatif.",negatif
"Il a bénéficié de beaucoup de favoritisme.",negatif
"Messi ne mérite pas tout le battage médiatique.",negatif
"Il est surévalué par ses fans.",negatif
"Messi n’est pas aussi décisif qu’on le croit.",negatif
"Il ne sait pas s’imposer dans toutes les situations.",negatif
"Messi est trop discret comme capitaine.",negatif
"Il n’a pas toujours montré de leadership.",negatif
"Messi s’efface trop vite quand ça devient dur.",negatif
"Il a échoué plusieurs fois dans les moments cruciaux.",negatif
"Messi est trop fragile mentalement.",negatif
"Il a toujours joué dans son confort.",negatif
"Messi n’est pas l’exemple idéal d’un leader.",negatif
"Il ne mérite pas tous ses trophées.",negatif
"Messi a souvent été en difficulté physiquement.",negatif
"Il n’a pas de polyvalence comme d’autres joueurs.",negatif
"Messi n’est pas irréprochable.",negatif
"Il est trop dépendant de son pied gauche.",negatif
"Messi n’est pas assez complet pour être le GOAT.",negatif
"Il n’a pas brillé dans toutes les compétitions.",negatif
"Messi manque de constance en sélection.",negatif
"Il n’est pas toujours performant sous pression.",negatif
"Messi est surprotégé médiatiquement.",negatif
"Il n’a pas dominé partout où il est allé.",negatif
"Messi est surcôté par la presse.",negatif
"Il ne s’est pas imposé en Ligue 1.",negatif
"Messi est moins influent avec l’âge.",negatif
"Il n’est pas le joueur parfait qu’on décrit.",negatif
"Messi a failli dans beaucoup de finales.",negatif
"Il a été sauvé par ses coéquipiers souvent.",negatif
"Messi ne joue pas assez pour l’équipe.",negatif
"Il n’a pas de charisme comme capitaine.",negatif
"Messi manque de personnalité.",negatif
"Il a échoué trop souvent avec l’Argentine.",negatif
"Messi n’est pas irréprochable dans les grands matchs.",negatif
"Il a eu la carrière facile.",negatif
"Messi est trop médiatisé.",negatif
"Il ne mérite pas son statut de légende.",negatif
"Messi a profité des circonstances.",negatif
"Il n’a pas toujours été à la hauteur.",negatif
"Messi est moins impressionnant que Ronaldo.",negatif
"Il ne mérite pas d’être appelé le meilleur.",negatif
"Messi a souvent failli sous pression.",negatif
"Il n’a pas été décisif en finale de LDC récentes.",negatif
"Messi est fragile dans les grands rendez-vous.",negatif
"Il n’a pas le même impact que d’autres légendes.",negatif
"Messi n’est pas un vrai leader naturel.",negatif
"Il est trop dépendant de son entourage.",negatif
"Messi est parfois invisible sur le terrain.",negatif
"Il a échoué en dehors de son club formateur.",negatif
"Messi n’a pas su se réinventer partout.",negatif
"Il n’est pas aussi constant qu’on le dit.",negatif
"Messi n’a pas été exceptionnel en France.",negatif
"Il n’a pas dominé chaque championnat.",negatif
"Messi n’a pas marqué tous les esprits.",negatif
"Il a échoué à plusieurs reprises avec son pays.",negatif
"Messi ne mérite pas tous ses Ballons d’Or.",negatif
"Il est trop mis en avant par les médias.",negatif
"Messi est moins décisif que d’autres légendes.",negatif
"Il a eu une carrière protégée.",negatif
"Messi est parfois transparent dans les matchs importants.",negatif
"Il n’est pas aussi grand qu’on le pense.",negatif
"Messi a échoué trop souvent en Coupe du Monde avant 2022.",negatif
"Il est surcoté par ses supporters.",negatif
"Messi n’est pas à la hauteur des attentes.",negatif"""]

In [42]:

#regex_positif=r"positif"
#commentaire_positif_clean=[]
#for element in commentaire_positif:
#    resultat_positif=re.findall(regex,element)
#    element=element.replace('positif','')
#    commentaire_positif_clean.append(element)
#commentaire_positif_clean
#Definition de la function clean pour retirer les element "positif" ou "negatif"
def clean_function(commentaire,replace_element):
    commentaire_clean=[]
    for element in commentaire:
        element=element.replace(replace_element,'')
        commentaire_clean.append(element)
    return commentaire_clean

In [43]:
positif="positif"
commentaire_positif_clean=clean_function(commentaire_positif,positif)
#commentaire_positif_clean

In [44]:
negatif="negatif"
commentaire_negatif_clean=clean_function(commentaire_negatif,negatif)
#commentaire_negatif_clean

In [159]:
#A utiliser plutart avec NLTK pour le stemming
comment_positif=clean_data(commentaire_positif_clean)
comment_negatif=clean_data(commentaire_negatif)

In [45]:
import csv
import numpy as np

In [48]:
#Enregistrement de nos données de commentaire positif dans notre fichier messi_commentaire_positif

header="content"
labels=np.ones(100)
with open("messi_commentaire_positif.csv","w",encoding="utf-8") as file:
    file.writelines(commentaire_positif_clean)
    

SyntaxError: invalid syntax (1182418989.py, line 2)

In [49]:
#Enregistrement de nos données de commentaire negatif dans notre fichier messi_commentaire_negatif
with open("messi_commentaire_negatif.csv","w",encoding="utf-8") as file:
    file.writelines(commentaire_negatif_clean)

In [50]:
#Enregistrement de nos données de commentaire negatif dans notre fichier messi_commentaire_negatif
with open("messi_commentaire.csv","w",encoding="utf-8") as file:
    file.writelines(commentaire_negatif_clean)
    file.writelines(commentaire_positif_clean)

In [172]:
#Ajout de fonction de netoyage 
def clean_data(commentaire):
    commentaire=''.join(commentaire)
    commentaire = commentaire.translate(str.maketrans('', '', string.punctuation))
    
    # 3. Supprimer les chiffres
    commentaire = re.sub(r'\d+', '', commentaire)
    
    # 4. Tokenisation simple (split par espace)
    commentaire = commentaire.split()
    return commentaire

In [52]:
#2.	Utiliser TF-IDF pour vectoriser le texte.
#Grace a notre liste commentaire_positif_clean et commentaire_negatif_clean on va directement tokeniser nos donner


In [173]:
import string
import spacy

#Tokenisation
nlp=spacy.load("fr_core_news_sm")

#Deja on va supprimer les poctuation
#Transformation de notre liste en string
def pretraitement_tokenisation(file_name):
    with open(file_name,"r",encoding='utf-8') as file:
        commentaire_clean=file.readlines()
        #netoyage
        commentaire_clean=clean_data(commentaire_clean)
        commentaire_clean=' '.join(commentaire_clean)
        commentaire_clean=nlp(commentaire_clean)
    return commentaire_clean
    


In [174]:
#Tokenisation du dataset à commentaire positif
titre_dataset_positif="messi_commentaire_positif.csv"

commentaire_positif_clean=pretraitement_tokenisation(titre_dataset_positif)

#commentaire_positif_clean
for token in commentaire_positif_clean:
    print(token.text," | ",token.pos_)

Messi  |  NOUN
est  |  AUX
un  |  DET
génie  |  NOUN
il  |  PRON
fait  |  VERB
rêver  |  VERB
le  |  DET
monde  |  NOUN
du  |  ADP
football  |  NOUN
Chaque  |  NOUN
fois  |  NOUN
qu’  |  SCONJ
il  |  PRON
touche  |  VERB
le  |  DET
ballon  |  NOUN
on  |  PRON
sent  |  VERB
la  |  DET
magie  |  NOUN
Il  |  PRON
est  |  AUX
une  |  DET
légende  |  ADJ
vivante  |  ADJ
incomparable  |  ADJ
dans  |  ADP
l’  |  NOUN
histoire  |  NOUN
du  |  ADP
sport  |  NOUN
Sa  |  DET
vision  |  NOUN
de  |  ADP
jeu  |  NOUN
est  |  AUX
exceptionnelle  |  VERB
il  |  PRON
fait  |  VERB
briller  |  VERB
toute  |  ADJ
son  |  DET
équipe  |  NOUN
Je  |  PRON
suis  |  AUX
impressionné  |  VERB
par  |  ADP
sa  |  DET
constance  |  NOUN
même  |  ADV
après  |  ADP
tant  |  ADV
d’  |  ADV
années  |  NOUN
Sans  |  ADP
Messi  |  PROPN
le  |  DET
football  |  NOUN
ne  |  ADV
serait  |  AUX
pas  |  ADV
le  |  DET
même  |  ADJ
Son  |  DET
humilité  |  NOUN
en  |  ADP
dehors  |  ADP
du  |  ADP
terrain  |  NOUN
le  |  PRO

In [180]:
#Tokenisation du dataset à commentaire negatif
titre_dataset_negatif="messi_commentaire_negatif.csv"
commentaire_negatif_clean=pretraitement_tokenisation(titre_dataset_negatif)
#commentaire_negatif_clean
for token in commentaire_negatif_clean:
    print(token.text," | ",token.pos_)
len(commentaire_negatif_clean_clean)

SyntaxError: incomplete input (78669242.py, line 7)

SyntaxError: incomplete input (78669242.py, line 7)

In [147]:
#Stemming  supprimer les préfixes et les suffixes, il coupe la fin ou le début des mot
#spaCy doesn't contain any function for stemming as it relies on lemmatization only
#We will use NLTK
import nltk

from nltk.stem.porter import *

In [148]:
#Importing PorterStemmer class
stemmer = PorterStemmer()

In [162]:
#Using Positive commentaire
for token in comment_positif:
    print(token ,'-------',stemmer.stem(token))

SyntaxError: incomplete input (1850891754.py, line 3)

In [164]:
#Using Negative commentaire
for token in comment_negatif:
    print(token ,'------->',stemmer.stem(token))

Messi -------> messi
est -------> est
trop -------> trop
surcoté -------> surcoté
il -------> il
n’a -------> n’a
pas -------> pa
prouvé -------> prouvé
dans -------> dan
toutes -------> tout
les -------> le
liguesnegatif -------> liguesnegatif
Il -------> il
disparaît -------> disparaît
souvent -------> souvent
dans -------> dan
les -------> le
grands -------> grand
matchsnegatif -------> matchsnegatif
Sans -------> san
Barcelone -------> barcelon
il -------> il
n’aurait -------> n’aurait
jamais -------> jamai
eu -------> eu
autant -------> autant
de -------> de
titresnegatif -------> titresnegatif
Il -------> il
n’a -------> n’a
pas -------> pa
la -------> la
même -------> même
influence -------> influenc
en -------> en
sélection -------> sélection
qu’en -------> qu’en
clubnegatif -------> clubnegatif
On -------> on
le -------> le
compare -------> compar
à -------> à
Pelé -------> pelé
et -------> et
Maradona -------> maradona
mais -------> mai
il -------> il
n’a -------> n’a
pas ---

In [177]:
#Lets Make Lemmatisation Using Spacy commentaire positif
commentaire_positif_clean_lem=[]
for lemm in commentaire_positif_clean:
    print(lemm.text,"------Lem------",lemm.lemma_)
    commentaire_positif_clean_lem.append(lemm.lemma_)


Messi ------Lem------ messi
est ------Lem------ être
un ------Lem------ un
génie ------Lem------ génie
il ------Lem------ il
fait ------Lem------ faire
rêver ------Lem------ rêver
le ------Lem------ le
monde ------Lem------ monde
du ------Lem------ de
football ------Lem------ football
Chaque ------Lem------ chaque
fois ------Lem------ fois
qu’ ------Lem------ qu’
il ------Lem------ il
touche ------Lem------ toucher
le ------Lem------ le
ballon ------Lem------ ballon
on ------Lem------ on
sent ------Lem------ sentir
la ------Lem------ le
magie ------Lem------ magie
Il ------Lem------ il
est ------Lem------ être
une ------Lem------ un
légende ------Lem------ légend
vivante ------Lem------ vivant
incomparable ------Lem------ incomparable
dans ------Lem------ dans
l’ ------Lem------ l’
histoire ------Lem------ histoire
du ------Lem------ de
sport ------Lem------ sport
Sa ------Lem------ son
vision ------Lem------ vision
de ------Lem------ de
jeu ------Lem------ jeu
est ------Lem------ être

In [181]:
#Lets Make Lemmatisation Using Spacy commentaire positif
commentaire_positif_clean_lem=[]
for lemm in commentaire_positif_clean:
    #print(lemm.text,"------Lem------",lemm.lemma_)
    commentaire_positif_clean_lem.append(lemm.lemma_)


In [182]:
#Lets Make Lemmatisation Using Spacy commentaire negatif
commentaire_negatif_clean_lem=[]
for lemm in commentaire_negatif_clean:
    #print(lemm.text,"------Lem------",lemm.lemma_)
    commentaire_negatif_clean_lem.append(lemm.lemma_)


In [ ]:
#Useful website:https://stackabuse.com/python-for-nlp-tokenization-stemming-and-lemmatization-with-spacy-library/

In [ ]:
#Now let's vectorise La vectorisation avec TfidfVectorizer (TF-IDF)

In [178]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [179]:
# Initialisation du TfidfVectorizer
vectorizer = TfidfVectorizer()

In [183]:
#Vectorisation des commentaire positif 
# Transformation du corpus en matrice TF-IDF
X_positif = vectorizer.fit_transform(commentaire_positif_clean_lem)

In [184]:
# Affichage de la matrice sous forme dense
print(X_positif.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [185]:
# Affichage du vocabulaire
print(vectorizer.vocabulary_)

{'messi': 123, 'être': 242, 'un': 226, 'génie': 78, 'il': 85, 'faire': 65, 'rêver': 193, 'le': 107, 'monde': 128, 'de': 43, 'football': 72, 'chaque': 32, 'fois': 70, 'qu': 170, 'toucher': 219, 'ballon': 18, 'on': 142, 'sentir': 198, 'magie': 115, 'légend': 113, 'vivant': 232, 'incomparable': 92, 'dans': 42, 'histoire': 80, 'sport': 205, 'son': 202, 'vision': 231, 'jeu': 101, 'exceptionnel': 62, 'briller': 25, 'tout': 221, 'équipe': 239, 'je': 100, 'impressionner': 89, 'par': 147, 'constance': 37, 'même': 136, 'après': 7, 'tant': 215, 'année': 5, 'sans': 194, 'ne': 137, 'pas': 149, 'humilité': 83, 'en': 55, 'dehors': 44, 'terrain': 218, 'rendre': 176, 'encore': 56, 'plus': 157, 'grand': 76, 'mérite': 134, 'largement': 106, 'ballons': 19, 'or': 143, 'définition': 52, 'mot': 131, 'taler': 214, 'voir': 234, 'jouer': 104, 'privilège': 165, 'pour': 160, 'notre': 141, 'génération': 79, 'technique': 216, 'simplement': 200, 'irréaliste': 98, 'pouvoir': 161, 'changer': 31, 'cours': 40, 'match': 

In [186]:
# Affichage des scores IDF
print(vectorizer.idf_)

[6.99520753 6.99520753 6.99520753 6.99520753 6.99520753 6.99520753
 6.99520753 6.99520753 6.99520753 6.99520753 6.99520753 6.0789168
 6.99520753 6.99520753 6.99520753 6.99520753 5.89659524 4.13300665
 6.30206035 6.99520753 6.99520753 6.99520753 6.58974243 6.58974243
 6.99520753 6.58974243 6.58974243 6.99520753 6.99520753 6.99520753
 6.99520753 6.58974243 5.60891317 6.99520753 6.99520753 6.99520753
 6.99520753 6.99520753 6.99520753 6.99520753 6.99520753 6.58974243
 5.49113014 3.88169222 6.99520753 6.99520753 6.99520753 6.99520753
 6.58974243 6.99520753 6.99520753 6.99520753 6.58974243 6.99520753
 6.99520753 6.0789168  6.99520753 6.99520753 5.89659524 6.99520753
 5.74244456 6.58974243 6.99520753 6.99520753 6.99520753 5.74244456
 6.30206035 6.99520753 6.58974243 6.58974243 6.99520753 6.99520753
 4.91576599 6.99520753 6.99520753 6.99520753 6.30206035 6.58974243
 6.99520753 5.89659524 5.89659524 6.99520753 6.99520753 6.99520753
 6.30206035 3.8171537  6.99520753 6.99520753 6.99520753 6.99520

In [187]:
#Vectorisation des commentaire negatif 
# Transformation du commentaire negatif  en matrice TF-IDF
X_negatif = vectorizer.fit_transform(commentaire_negatif_clean_lem)

In [188]:
# Affichage de la matrice sous forme dense
print(X_negatif.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [189]:
# Affichage du vocabulaire
print(vectorizer.vocabulary_)

{'messi': 132, 'être': 226, 'trop': 217, 'surcoter': 205, 'il': 98, 'avoir': 13, 'pas': 154, 'prouver': 175, 'dans': 48, 'tout': 214, 'le': 115, 'ligue': 118, 'disparaître': 59, 'souvent': 199, 'grand': 92, 'match': 128, 'sans': 191, 'barcelone': 16, 'jamais': 108, 'autant': 8, 'de': 49, 'titre': 212, 'même': 144, 'influence': 103, 'en': 69, 'sélection': 210, 'qu': 177, 'club': 32, 'on': 147, 'compare': 36, 'pelé': 156, 'et': 73, 'maradona': 126, 'mais': 123, 'impact': 99, 'historique': 95, 'ne': 146, 'défendre': 66, 'presque': 170, 'laisse': 113, 'travail': 216, 'autre': 10, 'son': 197, 'performance': 158, 'au': 6, 'psg': 176, 'décevanter': 62, 'dépendre': 67, 'coéquipier': 45, 'pour': 167, 'briller': 19, 'fragile': 85, 'physiquement': 162, 'se': 194, 'cache': 21, 'quand': 178, 'jeu': 109, 'devenir': 51, 'dur': 61, 'devoir': 52, 'gagner': 88, 'certain': 25, 'ballon': 14, 'or': 148, 'réussir': 190, 'imposer': 101, 'hors': 96, 'espagne': 71, 'toujours': 213, 'décisif': 64, 'coupe': 44, 

In [190]:
# Affichage des scores IDF
print(vectorizer.idf_)

[7.05208917 7.05208917 7.05208917 6.64662406 5.95347688 7.05208917
 7.05208917 5.95347688 7.05208917 7.05208917 5.7993262  6.13579844
 5.7993262  3.85341605 7.05208917 7.05208917 6.64662406 7.05208917
 6.64662406 6.35894199 7.05208917 7.05208917 6.64662406 6.64662406
 7.05208917 6.64662406 7.05208917 7.05208917 7.05208917 7.05208917
 6.64662406 7.05208917 6.64662406 7.05208917 7.05208917 6.13579844
 7.05208917 6.64662406 7.05208917 7.05208917 7.05208917 7.05208917
 7.05208917 7.05208917 6.64662406 6.64662406 7.05208917 7.05208917
 5.18028699 4.31124914 7.05208917 6.64662406 7.05208917 7.05208917
 7.05208917 7.05208917 7.05208917 7.05208917 7.05208917 6.64662406
 6.64662406 6.64662406 7.05208917 7.05208917 5.7993262  7.05208917
 7.05208917 6.13579844 7.05208917 5.03718615 7.05208917 6.64662406
 7.05208917 6.64662406 7.05208917 7.05208917 7.05208917 7.05208917
 6.64662406 7.05208917 7.05208917 7.05208917 6.35894199 6.64662406
 7.05208917 6.35894199 7.05208917 7.05208917 7.05208917 7.0520

In [195]:
#Now let's traine the model 3.	Entraîner un modèle de classification Naive Bayes pour prédire la classe d'un texte.
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

# -------------------
# 1. Créer dataset
# -------------------
# Fusionner les commentaires positifs et négatifs
X = commentaire_positif_clean_lem + commentaire_negatif_clean_lem
y = [1] * len(commentaire_positif_clean_lem) + [0] * len(commentaire_negatif_clean_lem)

# -------------------
# 2. Vectorisation
# -------------------
vectorizer = TfidfVectorizer()
X_vect = vectorizer.fit_transform(X)

# -------------------
# 3. Séparer en train/test
# -------------------
X_train, X_test, y_train, y_test = train_test_split(X_vect, y, test_size=0.2, random_state=42)

# -------------------
# 4. Entraîner Naive Bayes
# -------------------
model = MultinomialNB()
model.fit(X_train, y_train)

# -------------------
# 5. Évaluer le modèle
# -------------------
y_pred = model.predict(X_test)

print("Rapport de classification :")
print(classification_report(y_test, y_pred))

print("Matrice de confusion :")
print(confusion_matrix(y_test, y_pred))

# -------------------
# 6. Tester sur un nouveau commentaire
# -------------------
nouveau_commentaire = ["Messi es nul"]
nouveau_vect = vectorizer.transform(nouveau_commentaire)
prediction = model.predict(nouveau_vect)

print(" Prédiction :", "Positif" if prediction[0]==1 else "Négatif")


Rapport de classification :
              precision    recall  f1-score   support

           0       0.59      0.87      0.70       158
           1       0.79      0.45      0.57       173

    accuracy                           0.65       331
   macro avg       0.69      0.66      0.63       331
weighted avg       0.69      0.65      0.63       331

Matrice de confusion :
[[137  21]
 [ 96  77]]
 Prédiction : Négatif
